name: My Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
    - test
    types:
      closed 
    paths: 
    - test/**      

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Running Step 1"

      - name: Step 2
        run: echo "Running Step 2"

        # test comment